@startuml
hide methods
hide stereotypes
skinparam linetype ortho

entity "CLIENTE" as CLIENTE {
  pk, id, int
  , nombre, var char [50]
  , apellido, var char [50]
  , direccion_defecto, var char [50]
  fk, medio_pago_defecto_id, int
}

entity "RESTAURANTE" as RESTAURANTE {
  pk, id, int
  , nombre, var char [50]
  , direccion, var char [50]
  fk, zona_id, int
}

entity "PRODUCTO" as PRODUCTO {
  pk, id, int
  , nombre, var char [50]
  , precio, decimal
  , imagen_url, var char [50]
  , descripcion, var char [50]
  , tiempo_preparacion_estimado, int
  fk, restaurante_id, int
}

entity "CATEGORIA" as CATEGORIA {
  pk, id, int
  , nombre, var char [50]
  fk, producto_id, int
}

entity "PEDIDO" as PEDIDO {
  pk, id, int
  fk, cliente_id, int
  fk, restaurante_id, int
  fk, repartidor_id, int
  , direccion_entrega, var char [50]
  , costo_productos, decimal
  , costo_envio, decimal
  , comision_plataforma, decimal
  , propina, decimal
  , precio_final, decimal
  , fecha_hora, datetime
  , estado, var char [50]
  fk, medio_pago_id, int
}

entity "PEDIDO_ITEM" as PEDIDO_ITEM {
  pk fk, pedido_id, int
  pk fk, producto_id, int
  , cantidad, int
  , observacion, var char [50]
}

entity "REPARTIDOR" as REPARTIDOR {
  pk, id, int
  , nombre, var char [50]
  , apellido, var char [50]
  fk, zona_id, int
}

entity "ZONA" as ZONA {
  pk, id, int
  , nombre, var char [50]
}

entity "MEDIO_DE_PAGO" as MEDIO_DE_PAGO {
  pk, id, int
  , nombre, var char [50]
}

CLIENTE ||--o{ PEDIDO : "realiza"
RESTAURANTE ||--o{ PEDIDO : "recibe"
REPARTIDOR ||--o{ PEDIDO : "entrega"
RESTAURANTE ||--o{ PRODUCTO : "ofrece"
ZONA ||--o{ RESTAURANTE : "pertenece a"
ZONA ||--o{ REPARTIDOR : "trabaja en"
MEDIO_DE_PAGO ||--o{ PEDIDO : "pagado con"
CLIENTE ||--o{ MEDIO_DE_PAGO : "tiene por defecto"
CATEGORIA ||--o{ PRODUCTO

PEDIDO ||--|{ PEDIDO_ITEM : "compuesto por"
PRODUCTO ||--o{ PEDIDO_ITEM : "incluido en"

@enduml


